website/models.py
from . import db
from datetime import datetime

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    task = db.Column(db.String(60), unique = True)
    complete = db.Column(db.Boolean, default = False)
    category = db.Column(db.String(100))
    date = db.Column(db.DateTime, default=datetime.now)

    #! Creation of our Todo class. This will use inheritance to inherit db.Model
    #! The properties we have set above will become columns and set what data types the columns will be
    #! The id is set as a primary key because it is unique and unchanging and used to identify each row
    #! I have also set new columns for completing of task, task category and the date task was made

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__, static_url_path='/static')
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
    db.init_app(app)

    from .views import my_view
    app.register_blueprint(my_view)

    from .models import Todo
    with app.app_context():
        db.create_all()

    return app

#! The create_app function sets up and configures the Flask app.
#! Creates a Flask app instance and configures it to use the SQLite database.
#! Initialises the SQLAlchemy instance with the app.
#! Imports and registers a blueprint for organising the application.
#! It imports the Todo model and creates the necessary database tables within the app.
#! It will then return the configured Flask app.

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import Todo
from . import db

my_view = Blueprint("my_view", __name__)

@my_view.route("/")
def home():
    todo_list = Todo.query.all()
    print(todo_list)
    message = request.args.get('message', None)
    filter = request.args.get('filter_category') #! added a filter button so I can display the category selected.
    if filter:
        todo_list = Todo.query.filter_by(category=filter).all()
    
    return render_template("index.html", todo_list=todo_list, message=message)

@my_view.route("/add", methods=["POST"])
def add():
    try: #! Implemented error handling so that user can't input same task again using try/except
        task = request.form.get("task") #! This is a value of the variable task is retrieved from the HTML input named task
        category = request.form.get("category") #! This is also the same but for the category
        new_todo = Todo(task=task, category=category) #! This is a new instantiation of the class we made. The ID property is set automatically, and task and category are set to what the users chose.
        db.session.add(new_todo) #! We then at the new_todo objects to the database where it will become a new row in the table
        db.session.commit() #! Because of the changes the user made, we have to commit them to the database
        message = "Task added." #! Message displayed when user inputs new task
        return redirect(url_for("my_view.home", message = message)) #! At the end of the function, the app redirects us to the route mapped

    except:
        message = "Task already exists." #! Error message sent to notify user if inputted task has already been entered.
        return redirect(url_for("my_view.home", message=message)) #! This will also redirect us to the route mapped

@my_view.route("/update/<todo_id>") #! Creation of our new route
def update(todo_id): #! Calling the function the same as our route which will take the todo ID as an argument
    todo = Todo.query.filter_by(id=todo_id).first() #! The object we want to update is the first result that matches the ID we give to the function when we query the database
    todo.complete = not todo.complete #! Update the complete property to the opposite of what it currently is.
    db.session.commit() #! Commit the change to the database.
    return redirect(url_for("my_view.home")) #! Return to the route of home.

@my_view.route("/delete/<todo_id>") #! New route created for deleting. This is also the exact same as updating but we use dot notation to delete it and then commit it to the database.
def delete(todo_id):
    todo = Todo.query.filter_by(id=todo_id).first()
    db.session.delete(todo)
    db.session.commit()
    message = "Task deleted."
    return redirect(url_for("my_view.home", message=message))

@my_view.route("/edit/<todo_id>", methods = ["GET", "POST"]) #! New route created to edit tasks using both the GET and POST methods.
def edit(todo_id):
    try: #! Try/except used for error handling
        todo = Todo.query.filter_by(id=todo_id).first() #! This will be matching the ID we give to the function when we query the database.
        if request.method == "POST": #! This if statement checks if the request method is POST.
            updated_task = request.form.get("task") #! We will use .get to retrieve the updated task and category from the user
            updated_category = request.form.get("category")
            if updated_task and updated_category: #! checking if both are not empty.
                todo.task = updated_task
                todo.category = updated_category
                db.session.commit() #! It will then commit all the changes and change them on the database.
                message = "Task updated."
                return redirect(url_for("my_view.home", message = message)) #! This will then redirect them to the home page and display the message that the task has been updated
    except:
        message = "Task cannot be empty or the same." #! Task cannot be the same or empty and message will be displayed.
        return redirect(url_for("my_view.home", message = message))
    return render_template("edit.html", todo = todo) #! Will then pass the todo object and will return to the home page with changes made.

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" /><link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded" rel="stylesheet">

</head>
 
<!-- BOILER PLATE FOR ALL PAGES ^^^^^^ -->

<body>

{% block content %}

<!-- CONTENT FOR PAGES WILL APPEAR IN THIS BLOCK -->

{% endblock %}

</body>

</html>

website/templates/edit.html
{% extends 'base.html' %}

<!-- EXTENDING MY BOILER PLATE TO THIS PAGE -->

{% block content %}

    <div class="container">
        <h1>Edit Task</h1>
        <form action="{{ url_for('my_view.edit', todo_id=todo.id) }}" method="POST"> <!-- THIS WILL POST THE UPDATED TASKS-->
            <div>
                <input type="text" id="task" name="task" value="{{ todo.task }}" placeholder="Edit task">
                <select required name="category" id="category" class="form-select">
                    <option value="" disabled selected hidden>Choose category...</option>
                    <option value="Work">Work</option>
                    <option value="Home">Home</option>
                    <option value="Personal">Personal</option>
                    <option value="Health">Health</option>
                    <option value="Other">Other</option> <!-- ALL OPTIONS FOR THE USER TO PICK WHAT CATEGORY THEIR TASK FALLS INTO-->
                  </select>
            </div>
            <div class="button-container">
                <button class="ui button green" type="submit" ><span class="material-symbols-rounded">
                    add
                    </span></button> <!-- CLICKING UPDATE WILL UPDATE THE INFORMATION-->
                <a class="ui button purple" href="{{ url_for('my_view.home') }}"><span class="material-symbols-rounded">
                    arrow_back
                    </span></a> <!-- PRESSING RETURN WILL TAKE THEM BACK TO HOMEPAGE-->
            </div>
        </form>
    </div>

    {% endblock %}

website/templates/index.html
{% extends 'base.html' %}

<!-- EXTENDING MY BOILER PLATE TO THIS PAGE -->

{% block content %}
    
    <div class="container">
        <section id="top_of_page">
        <h1>To Do List</h1>
        
        <form action="/add" method="post">
            <div>
                <label>Just do it!</label>
                <input type="text" name="task" placeholder="Enter a Task..." required> <!-- FORMS FOR USER INPUTS TO CHOOSE -->
                <select required name="category" id="category" class="form-select">
                    <option value="" disabled selected hidden>Choose category...</option>
                    <option value="Work">Work</option>
                    <option value="Home">Home</option>
                    <option value="Personal">Personal</option>
                    <option value="Health">Health</option>
                    <option value="Other">Other</option>
                  </select>
                <button class="ui button green" type="submit" ><span class="material-symbols-rounded">
                    add
                    </span></button>
                {% if message %} <!-- MESSAGE TO DISPLAY ONCE TASK HAS BEEN ADDED-->
                <p>{{message}}</p>
                {% endif %}
            </div>
        </form>
    </section>
        <hr>
        <form action="/" method="get" class="filter-form">
            <div class="filter-controls">
                <select name="filter_category" id="filter_category" class="form-select">
                    <option value="">All categories</option>
                    <option value="Work">Work</option>
                    <option value="Home">Home</option>
                    <option value="Personal">Personal</option>
                    <option value="Health">Health</option>
                    <option value="Other">Other</option>
                </select>
                <button type="submit" class="ui label filter-label"><span class="material-symbols-rounded">filter_list</span></button>
            </div>
        </form>
        
        {% for todo in todo_list %} <!-- ITERATE THROUGH THE OUR TODO-->
        <div class="ui segment">
            <div class="header-container">
            <p>#</p>
            <p>TASK</p>
            <p>CATEGORY</p>
            <p>DATE</p>
            </div>
            <div class="task-container">
            <p>{{todo.id}}</p>
            <p>{{todo.task}}</p>
            <p>{{todo.category}}</p>
            <p>{{todo.date.strftime("%d/%m/%y")}}</p>
            </div>
            {% if todo.complete == False %}
            <span class="ui gray label filter">
                <span class="material-symbols-rounded">close</span>
            </span> <!-- MARKING THE TASK DONE AS COMPLETE-->
            {% else %}
            <span class="ui green label">
                <span class="material-symbols-rounded">check</span>
            </span>
            {% endif %}

            <a class="ui blue button" href="{{ url_for('my_view.update', todo_id = todo.id) }}">
                <span class="material-symbols-rounded">update</span>
            </a>
            <a class="ui yellow button" href="{{ url_for('my_view.edit', todo_id=todo.id) }}">
                <span class="material-symbols-rounded">edit</span>
            </a>
            <a class="ui red button"  href="{{ url_for('my_view.delete', todo_id = todo.id) }}">
                <span class="material-symbols-rounded">delete</span>
            </a>
        </div>
        
        {% endfor %}
        
        <a href="#top_of_page" class="back-to-top">
            <span class="material-icons">keyboard_arrow_up</span>
        </a>
    </div>
    
    {% endblock %}